/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaPrincipal;

import Espacio.ControladorEspacio;
import contrato.ControladorContratos;
import contrato.FrmBuscarContrato;
import contrato.FrmContratos;
import contrato.GestorCliente;
import contrato.GestorContratos;
import empleados.ControladorEmpleado;
import empleados.FrmbuscarEmpleado;
import empleados.gestorEmpleado;
import empleados.registroEmpleado;
import Espacio.FrmEspacio;
import Espacio.FrmBuscarEspacio;
import serviciosAdicionales.ControladorServicio;
import serviciosAdicionales.FrmServicio;
import serviciosAdicionales.frmBuscarServicio;
import serviciosAdicionales.gestorServicio;
import Espacio.GestorEspacios;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuModulos = new javax.swing.JMenu();
        MenuClientes = new javax.swing.JMenuItem();
        MenuEmpleados = new javax.swing.JMenuItem();
        MenuEspacios = new javax.swing.JMenuItem();
        MenuServiciosAdicionales = new javax.swing.JMenuItem();
        MenuContratos = new javax.swing.JMenuItem();
        MenuBuscar = new javax.swing.JMenu();
        MenuBuscarCliente = new javax.swing.JMenuItem();
        MenuBuscarEmpleados = new javax.swing.JMenuItem();
        MenuBuscarEspacios = new javax.swing.JMenuItem();
        MenuBuscarServicios = new javax.swing.JMenuItem();
        MenuBuscarContratos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuModulos.setText("Modulos");

        MenuClientes.setText("Clientes");
        MenuClientes.addActionListener(this::MenuClientesActionPerformed);
        MenuModulos.add(MenuClientes);

        MenuEmpleados.setText("Empleados");
        MenuEmpleados.addActionListener(this::MenuEmpleadosActionPerformed);
        MenuModulos.add(MenuEmpleados);

        MenuEspacios.setText("Espacios");
        MenuEspacios.addActionListener(this::MenuEspaciosActionPerformed);
        MenuModulos.add(MenuEspacios);

        MenuServiciosAdicionales.setText("Servicios Adicionales");
        MenuServiciosAdicionales.addActionListener(this::MenuServiciosAdicionalesActionPerformed);
        MenuModulos.add(MenuServiciosAdicionales);

        MenuContratos.setText("Contratos");
        MenuContratos.addActionListener(this::MenuContratosActionPerformed);
        MenuModulos.add(MenuContratos);

        jMenuBar1.add(MenuModulos);

        MenuBuscar.setText("Buscar");

        MenuBuscarCliente.setText("Buscar Cliente");
        MenuBuscarCliente.addActionListener(this::MenuBuscarClienteActionPerformed);
        MenuBuscar.add(MenuBuscarCliente);

        MenuBuscarEmpleados.setText("Buscar Emleado");
        MenuBuscarEmpleados.addActionListener(this::MenuBuscarEmpleadosActionPerformed);
        MenuBuscar.add(MenuBuscarEmpleados);

        MenuBuscarEspacios.setText("Buscar Espacios");
        MenuBuscarEspacios.addActionListener(this::MenuBuscarEspaciosActionPerformed);
        MenuBuscar.add(MenuBuscarEspacios);

        MenuBuscarServicios.setText("Buscar Servicios Adicionales");
        MenuBuscarServicios.addActionListener(this::MenuBuscarServiciosActionPerformed);
        MenuBuscar.add(MenuBuscarServicios);

        MenuBuscarContratos.setText("Buscar Contratos");
        MenuBuscarContratos.addActionListener(this::MenuBuscarContratosActionPerformed);
        MenuBuscar.add(MenuBuscarContratos);

        jMenuBar1.add(MenuBuscar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuServiciosAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuServiciosAdicionalesActionPerformed
        new FrmServicio().setVisible(true);
    }//GEN-LAST:event_MenuServiciosAdicionalesActionPerformed

    private void MenuContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContratosActionPerformed
        new FrmContratos().setVisible(true);
    }//GEN-LAST:event_MenuContratosActionPerformed

    private void MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesActionPerformed
        JOptionPane.showMessageDialog(this, "Módulo de Clientes no disponible aún.");
    }//GEN-LAST:event_MenuClientesActionPerformed

    private void MenuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmpleadosActionPerformed
        new registroEmpleado().setVisible(true);
    }//GEN-LAST:event_MenuEmpleadosActionPerformed

    private void MenuEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEspaciosActionPerformed
        new FrmEspacio().setVisible(true);
    }//GEN-LAST:event_MenuEspaciosActionPerformed

    private void MenuBuscarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarServiciosActionPerformed
        gestorServicio gestor = new gestorServicio();
        ControladorServicio controlador = new ControladorServicio(gestor);
        new frmBuscarServicio(controlador, null).setVisible(true);
    }//GEN-LAST:event_MenuBuscarServiciosActionPerformed

    private void MenuBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarClienteActionPerformed
        JOptionPane.showMessageDialog(this, "Módulo de Búsqueda de Clientes no disponible aún.");
    }//GEN-LAST:event_MenuBuscarClienteActionPerformed

    private void MenuBuscarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarEmpleadosActionPerformed
        gestorEmpleado gestor = new gestorEmpleado();
        ControladorEmpleado controlador = new ControladorEmpleado(gestor);
        new FrmbuscarEmpleado(controlador, null).setVisible(true);
    }//GEN-LAST:event_MenuBuscarEmpleadosActionPerformed

    private void MenuBuscarEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarEspaciosActionPerformed
        new FrmBuscarEspacio().setVisible(true);
    }//GEN-LAST:event_MenuBuscarEspaciosActionPerformed

    private void MenuBuscarContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarContratosActionPerformed
        new FrmBuscarContrato().setVisible(true);
    }//GEN-LAST:event_MenuBuscarContratosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBuscar;
    private javax.swing.JMenuItem MenuBuscarCliente;
    private javax.swing.JMenuItem MenuBuscarContratos;
    private javax.swing.JMenuItem MenuBuscarEmpleados;
    private javax.swing.JMenuItem MenuBuscarEspacios;
    private javax.swing.JMenuItem MenuBuscarServicios;
    private javax.swing.JMenuItem MenuClientes;
    private javax.swing.JMenuItem MenuContratos;
    private javax.swing.JMenuItem MenuEmpleados;
    private javax.swing.JMenuItem MenuEspacios;
    private javax.swing.JMenu MenuModulos;
    private javax.swing.JMenuItem MenuServiciosAdicionales;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}