/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaPrincipal;

import contrato.FrmBuscarContrato;
import contrato.FrmContratos;
import empleados.ControladorEmpleado;
import empleados.FrmbuscarEmpleado;
import empleados.gestorEmpleado;
import empleados.registroEmpleado;
import Espacio.FrmEspacio;
import Espacio.FrmBuscarEspacio;
import serviciosAdicionales.ControladorServicio;
import serviciosAdicionales.FrmServicio;
import serviciosAdicionales.frmBuscarServicio;
import serviciosAdicionales.gestorServicio;
import clientes.FrmCliente;

/**
 *
 * @author USER
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        frmBuscarCliente1 = new clientes.FrmBuscarCliente();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuModulos = new javax.swing.JMenu();
        MenuClientes = new javax.swing.JMenuItem();
        MenuEmpleados = new javax.swing.JMenuItem();
        MenuEspacios = new javax.swing.JMenuItem();
        MenuServiciosAdicionales = new javax.swing.JMenuItem();
        MenuContratos = new javax.swing.JMenuItem();
        MenuBuscar = new javax.swing.JMenu();
        MenuBuscarCliente = new javax.swing.JMenuItem();
        MenuBuscarEmpleados = new javax.swing.JMenuItem();
        MenuBuscarEspacios = new javax.swing.JMenuItem();
        MenuBuscarServicios = new javax.swing.JMenuItem();
        MenuBuscarContratos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frmBuscarCliente1.setVisible(false);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        jDesktopPane1.setLayer(frmBuscarCliente1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(493, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmBuscarCliente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(frmBuscarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        MenuModulos.setText("Modulos");

        MenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos32/emblem-people.png"))); // NOI18N
        MenuClientes.setText("Clientes");
        MenuClientes.addActionListener(this::MenuClientesActionPerformed);
        MenuModulos.add(MenuClientes);

        MenuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos48/contacts.png"))); // NOI18N
        MenuEmpleados.setText("Empleados");
        MenuEmpleados.addActionListener(this::MenuEmpleadosActionPerformed);
        MenuModulos.add(MenuEmpleados);

        MenuEspacios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos32/emblem-package.png"))); // NOI18N
        MenuEspacios.setText("Espacios");
        MenuEspacios.addActionListener(this::MenuEspaciosActionPerformed);
        MenuModulos.add(MenuEspacios);

        MenuServiciosAdicionales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos48/add_48.png"))); // NOI18N
        MenuServiciosAdicionales.setText("Servicios Adicionales");
        MenuServiciosAdicionales.addActionListener(this::MenuServiciosAdicionalesActionPerformed);
        MenuModulos.add(MenuServiciosAdicionales);

        MenuContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos48/application_vnd.oasis.opendocument.spreadsheet (4).png"))); // NOI18N
        MenuContratos.setText("Contratos");
        MenuContratos.addActionListener(this::MenuContratosActionPerformed);
        MenuModulos.add(MenuContratos);

        jMenuBar1.add(MenuModulos);

        MenuBuscar.setText("Buscar");

        MenuBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos24/Search.png"))); // NOI18N
        MenuBuscarCliente.setText("Buscar Cliente");
        MenuBuscarCliente.addActionListener(this::MenuBuscarClienteActionPerformed);
        MenuBuscar.add(MenuBuscarCliente);

        MenuBuscarEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos24/Search.png"))); // NOI18N
        MenuBuscarEmpleados.setText("Buscar Emleado");
        MenuBuscarEmpleados.addActionListener(this::MenuBuscarEmpleadosActionPerformed);
        MenuBuscar.add(MenuBuscarEmpleados);

        MenuBuscarEspacios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos24/Search.png"))); // NOI18N
        MenuBuscarEspacios.setText("Buscar Espacios");
        MenuBuscarEspacios.addActionListener(this::MenuBuscarEspaciosActionPerformed);
        MenuBuscar.add(MenuBuscarEspacios);

        MenuBuscarServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos24/Search.png"))); // NOI18N
        MenuBuscarServicios.setText("Buscar Servicios Adicionales");
        MenuBuscarServicios.addActionListener(this::MenuBuscarServiciosActionPerformed);
        MenuBuscar.add(MenuBuscarServicios);

        MenuBuscarContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos24/Search.png"))); // NOI18N
        MenuBuscarContratos.setText("Buscar Contratos");
        MenuBuscarContratos.addActionListener(this::MenuBuscarContratosActionPerformed);
        MenuBuscar.add(MenuBuscarContratos);

        jMenuBar1.add(MenuBuscar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuServiciosAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuServiciosAdicionalesActionPerformed
        new FrmServicio().setVisible(true);
    }//GEN-LAST:event_MenuServiciosAdicionalesActionPerformed

    private void MenuContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContratosActionPerformed
        new FrmContratos().setVisible(true);
    }//GEN-LAST:event_MenuContratosActionPerformed

    private void MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesActionPerformed
        new FrmCliente().setVisible(true);
    }//GEN-LAST:event_MenuClientesActionPerformed

    private void MenuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmpleadosActionPerformed
        new registroEmpleado().setVisible(true);
    }//GEN-LAST:event_MenuEmpleadosActionPerformed

    private void MenuEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEspaciosActionPerformed
        new FrmEspacio().setVisible(true);
    }//GEN-LAST:event_MenuEspaciosActionPerformed

    private void MenuBuscarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarServiciosActionPerformed
        gestorServicio gestor = new gestorServicio();
        ControladorServicio controlador = new ControladorServicio(gestor);
        new frmBuscarServicio(controlador, null).setVisible(true);
    }//GEN-LAST:event_MenuBuscarServiciosActionPerformed

    private void MenuBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarClienteActionPerformed
        frmBuscarCliente1.setVisible(true);
    }//GEN-LAST:event_MenuBuscarClienteActionPerformed

    private void MenuBuscarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarEmpleadosActionPerformed
        gestorEmpleado gestor = new gestorEmpleado();
        ControladorEmpleado controlador = new ControladorEmpleado(gestor);
        new FrmbuscarEmpleado(controlador, null).setVisible(true);
    }//GEN-LAST:event_MenuBuscarEmpleadosActionPerformed

    private void MenuBuscarEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarEspaciosActionPerformed
        new FrmBuscarEspacio().setVisible(true);
    }//GEN-LAST:event_MenuBuscarEspaciosActionPerformed

    private void MenuBuscarContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarContratosActionPerformed
        new FrmBuscarContrato().setVisible(true);
    }//GEN-LAST:event_MenuBuscarContratosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBuscar;
    private javax.swing.JMenuItem MenuBuscarCliente;
    private javax.swing.JMenuItem MenuBuscarContratos;
    private javax.swing.JMenuItem MenuBuscarEmpleados;
    private javax.swing.JMenuItem MenuBuscarEspacios;
    private javax.swing.JMenuItem MenuBuscarServicios;
    private javax.swing.JMenuItem MenuClientes;
    private javax.swing.JMenuItem MenuContratos;
    private javax.swing.JMenuItem MenuEmpleados;
    private javax.swing.JMenuItem MenuEspacios;
    private javax.swing.JMenu MenuModulos;
    private javax.swing.JMenuItem MenuServiciosAdicionales;
    private javax.swing.JButton btnSalir;
    private clientes.FrmBuscarCliente frmBuscarCliente1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}