/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Espacio;

import excepciones.EspacioOcupadoException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmBuscarEspacio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBuscarEspacio.class.getName());
    private final ControladorEspacio controladorEspacio;

    /**
     * Creates new form FrmBuscarEspacio
     */
    public FrmBuscarEspacio() {
        this(new ControladorEspacio());
    }

    public FrmBuscarEspacio(ControladorEspacio controladorEspacio) {
        if (controladorEspacio == null) {
            throw new IllegalArgumentException("El controlador de espacios es obligatorio.");
        }
        this.controladorEspacio = controladorEspacio;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configurarTabla();
        buscarEspacios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFiltroPrecioMin = new javax.swing.JTextField();
        txtFiltroNumero = new javax.swing.JTextField();
        txtFiltroPrecioMax = new javax.swing.JTextField();
        cbmFiltroTipo = new javax.swing.JComboBox<>();
        cbmFiltroDisponible = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspacios = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar espacios");

        jLabel2.setText("Precio mín");

        jLabel3.setText("Número");

        jLabel4.setText("Tipo");

        jLabel5.setText("Precio máx ");

        jLabel6.setText("Disponibilidad");

        txtFiltroPrecioMax.addActionListener(this::txtFiltroPrecioMaxActionPerformed);

        cbmFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "PEQUEÑO", "MEDIANO", "GRANDE" }));

        cbmFiltroDisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Disponible", "Ocupado" }));

        tblEspacios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblEspacios);

        btnLimpiar.setText("Limpiar filtros");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnNuevo.setText("Nuevo espacio");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnEliminar.setText("Eliminar seleccionado");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFiltroNumero)
                                .addComponent(txtFiltroPrecioMin, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFiltroPrecioMax, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbmFiltroTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbmFiltroDisponible, 0, 144, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbmFiltroTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txtFiltroNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbmFiltroDisponible, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltroPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltroPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroPrecioMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroPrecioMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroPrecioMaxActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarEspacios();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblEspacios.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un espacio de la tabla.",
                    "Sin selección", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int numeroEspacio = (Integer) tblEspacios.getValueAt(filaSeleccionada, 0);
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Desea eliminar el espacio " + numeroEspacio + "?", "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            controladorEspacio.eliminarEspacio(numeroEspacio);
            JOptionPane.showMessageDialog(this, "Espacio eliminado correctamente.", "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
            buscarEspacios();
        } catch (EspacioOcupadoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "No se puede eliminar",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        FrmEspacio ventanaEspacio = new FrmEspacio(controladorEspacio);
        ventanaEspacio.setLocationRelativeTo(this);
        ventanaEspacio.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtFiltroNumero.setText("");
        txtFiltroPrecioMin.setText("");
        txtFiltroPrecioMax.setText("");
        cbmFiltroTipo.setSelectedIndex(0);
        cbmFiltroDisponible.setSelectedIndex(0);
        buscarEspacios();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void configurarTabla() {
        tblEspacios.setModel(new DefaultTableModel(
                new Object[]{"Número", "Tipo", "Tamaño (m²)", "Precio mensual (₡)", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        });
    }

    private void buscarEspacios() {
        try {
            Integer numero = convertirEnteroOpcional(txtFiltroNumero.getText());
            Double precioMinimo = convertirDecimalOpcional(txtFiltroPrecioMin.getText());
            Double precioMaximo = convertirDecimalOpcional(txtFiltroPrecioMax.getText());
            TipoEspacio tipo = convertirTipoFiltro();
            Boolean disponible = convertirDisponibilidadFiltro();

            List<Espacios> espacios = controladorEspacio.buscarConFiltros(numero, tipo,
                    disponible, precioMinimo, precioMaximo);
            cargarTabla(espacios);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Número y precios deben contener valores numéricos válidos.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarTabla(List<Espacios> espacios) {
        DefaultTableModel modelo = (DefaultTableModel) tblEspacios.getModel();
        modelo.setRowCount(0);
        for (Espacios espacio : espacios) {
            modelo.addRow(new Object[]{
                espacio.getNumeroEspacio(),
                espacio.getTipo(),
                espacio.getTamaño(),
                espacio.getPrecioMensual(),
                espacio.isDisponible() ? "Disponible" : "Ocupado"
            });
        }
    }

    private Integer convertirEnteroOpcional(String texto) {
        String valor = texto.trim();
        return valor.isEmpty() ? null : Integer.valueOf(valor);
    }

    private Double convertirDecimalOpcional(String texto) {
        String valor = texto.trim();
        return valor.isEmpty() ? null : Double.valueOf(valor);
    }

    private TipoEspacio convertirTipoFiltro() {
        String tipoSeleccionado = (String) cbmFiltroTipo.getSelectedItem();
        return "Todos".equals(tipoSeleccionado) ? null : TipoEspacio.valueOf(tipoSeleccionado);
    }

    private Boolean convertirDisponibilidadFiltro() {
        String disponibilidad = (String) cbmFiltroDisponible.getSelectedItem();
        if ("Disponible".equals(disponibilidad)) {
            return true;
        }
        if ("Ocupado".equals(disponibilidad)) {
            return false;
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmBuscarEspacio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbmFiltroDisponible;
    private javax.swing.JComboBox<String> cbmFiltroTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEspacios;
    private javax.swing.JTextField txtFiltroNumero;
    private javax.swing.JTextField txtFiltroPrecioMax;
    private javax.swing.JTextField txtFiltroPrecioMin;
    // End of variables declaration//GEN-END:variables
}
