/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serviciosAdicionales;
import excepciones.ServicioNoencontradoException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author EMMAXZZ
 */
public class frmBuscarServicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmBuscarServicio.class.getName());
    private ControladorServicio controlador;
    private FrmServicio frmServicio;
    /**
     * Creates new form frmBuscarServicio
     */
    public frmBuscarServicio(ControladorServicio controlador, FrmServicio frmServicio) {
        initComponents();
        
     this.controlador = controlador;
     this.frmServicio = frmServicio;
   
     tablabuscar();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnbusc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTableSer = new javax.swing.JTable();
        btnacep = new javax.swing.JButton();
        btncance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        btnbusc.setText("Buscar");
        btnbusc.addActionListener(this::btnbuscActionPerformed);

        tbTableSer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripción", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tbTableSer);

        btnacep.setText("Aceptar");
        btnacep.addActionListener(this::btnacepActionPerformed);

        btncance.setText("Cancelar");
        btncance.addActionListener(this::btncanceActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfcode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addComponent(btnbusc))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnacep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncance)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbusc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnacep)
                    .addComponent(btncance))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablabuscar(){
        DefaultTableModel tabla = (DefaultTableModel) tbTableSer.getModel();
        tabla.setRowCount(0);
          for (ServicioAdicional servicio : controlador.getServicios()) {
            tabla.addRow(new Object[]{
            servicio.getCodigo(),
            servicio.getNombre(),
            servicio.getDescripcion(),
            servicio.getPrecio()
        });
    }
          }
    
    
    private void btnbuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscActionPerformed
        try {
        int codigo = Integer.parseInt(txfcode.getText());
        ServicioAdicional servicio = controlador.buscarServicio(codigo);
        DefaultTableModel buscar = (DefaultTableModel) tbTableSer.getModel();
        buscar.setRowCount(0);

        buscar.addRow(new Object[]{
            servicio.getCodigo(),
            servicio.getNombre(),
            servicio.getDescripcion(),
            servicio.getPrecio()
        });

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El código debe ser un número");
    } catch (ServicioNoencontradoException F) {
        JOptionPane.showMessageDialog(this, F.getMessage());
    }
    }//GEN-LAST:event_btnbuscActionPerformed

    private void btncanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanceActionPerformed
        dispose();
    }//GEN-LAST:event_btncanceActionPerformed

    private void btnacepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacepActionPerformed
     int F = tbTableSer.getSelectedRow();

    if (F == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un servicio");
    } else {
        try {
            int codigo = Integer.parseInt(tbTableSer.getValueAt(F, 0).toString());
            ServicioAdicional servicio = controlador.buscarServicio(codigo);
            frmServicio.cargarServicio(servicio);
            dispose();
        } catch (ServicioNoencontradoException NO) {
            JOptionPane.showMessageDialog(this, NO.getMessage());
        }
    }
    }//GEN-LAST:event_btnacepActionPerformed
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacep;
    private javax.swing.JButton btnbusc;
    private javax.swing.JButton btncance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbTableSer;
    private javax.swing.JTextField txfcode;
    // End of variables declaration//GEN-END:variables
}
