/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serviciosAdicionales;

import excepciones.ServicioNoencontradoException;
import javax.swing.JOptionPane;

/**
 *
 * @author EMMAXZZ
 */
public class FrmServicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmServicio.class.getName());
    private gestorServicio gestor;
    private ControladorServicio controlador;
    /**
     * Creates new form FrmServicio
     */
    public FrmServicio() {
        initComponents();
        
         gestor = new gestorServicio();
    controlador = new ControladorServicio(gestor);

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfNomb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfPrec = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();

        jLabel1.setText("Codigo:");

        txfcode.setEditable(false);

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Descripción:");

        txfDesc.addActionListener(this::txfDescActionPerformed);

        jLabel4.setText("Precio:");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(this::btGuardarActionPerformed);

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(this::btActualizarActionPerformed);

        bteliminar.setText("Eliminar");
        bteliminar.addActionListener(this::bteliminarActionPerformed);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(this::btBuscarActionPerformed);

        btLimpiar.setText("Limpiar campos");
        btLimpiar.addActionListener(this::btLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txfcode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txfNomb)
                        .addComponent(jLabel3)
                        .addComponent(txfDesc)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfPrec))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btGuardar)
                            .addComponent(bteliminar))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btActualizar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                                .addComponent(btLimpiar)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txfDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfPrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bteliminar)
                    .addComponent(btBuscar)
                    .addComponent(btLimpiar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void cargarServicio(ServicioAdicional servicio) {

    txfcode.setText(String.valueOf(servicio.getCodigo()));
    txfNomb.setText(servicio.getNombre());
    txfDesc.setText(servicio.getDescripcion());
    txfPrec.setText(String.valueOf(servicio.getPrecio()));
}
    
    private void txfDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDescActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
      txfcode.setText("");
      txfNomb.setText("");       
      txfDesc.setText("");       
      txfPrec.setText("");       
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
      try{
          String nombre = txfNomb.getText();
          String desc = txfDesc.getText();
          double precio = Double.parseDouble(txfPrec.getText());
          
          controlador.agregarServicio(nombre, desc, precio);
          JOptionPane.showMessageDialog(this, "Servicio guardado correctamente");
      }catch(NumberFormatException S){
          JOptionPane.showMessageDialog(this, "El precio debe ser un numero");
      }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        try{
            int codigo = Integer.parseInt(txfcode.getText());
            String desc = txfDesc.getText();
            double precio = Double.parseDouble(txfPrec.getText());
            controlador.actualizarServicio(codigo, desc, precio);
            JOptionPane.showMessageDialog(this, "Se actualizo correctamente");
        }catch(ServicioNoencontradoException S){
            JOptionPane.showMessageDialog(this, S.getMessage());
        }catch(NumberFormatException N){
            JOptionPane.showMessageDialog(this," El precio debe ser un numero");
        }
    }//GEN-LAST:event_btActualizarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        try{
            int codigo = Integer.parseInt(txfcode.getText());
            controlador.eliminarServicio(codigo);
            JOptionPane.showMessageDialog(this, "Se elimino el servicio correctamente");
        }  catch (ServicioNoencontradoException s) {
             JOptionPane.showMessageDialog(this,s.getMessage());
        }catch (NumberFormatException N) {
            JOptionPane.showMessageDialog(this, "El codigo debe ser un numero");
        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
       
        frmBuscarServicio buscar = new frmBuscarServicio(controlador,this);
         buscar.setVisible(true);
    }//GEN-LAST:event_btBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmServicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txfDesc;
    private javax.swing.JTextField txfNomb;
    private javax.swing.JTextField txfPrec;
    private javax.swing.JTextField txfcode;
    // End of variables declaration//GEN-END:variables
}
