/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empleados;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author EMMAXZZ
 */
public class FrmbuscarEmpleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmbuscarEmpleado.class.getName());
    private ControladorEmpleado controlador;
    private registroEmpleado frmEmpleado;
    /**
     * Creates new form FrmbuscarEmpleado
     */
    public FrmbuscarEmpleado(ControladorEmpleado controlador, registroEmpleado frmEmpleado) {
        initComponents();
        
        this.controlador = controlador;
         this.frmEmpleado = frmEmpleado; 
        llenarpuesto();
        tablabuscar();

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxpues = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbusca = new javax.swing.JTable();
        btbusca = new javax.swing.JButton();
        btacep = new javax.swing.JButton();
        btcanc = new javax.swing.JButton();

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre completo:");

        jLabel3.setText("Puesto:");

        cbxpues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxpues.addActionListener(this::cbxpuesActionPerformed);

        tblbusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Puesto", "Salario"
            }
        ));
        jScrollPane1.setViewportView(tblbusca);

        btbusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos48/deskbar-applet.png"))); // NOI18N
        btbusca.setText("Bucar");
        btbusca.addActionListener(this::btbuscaActionPerformed);

        btacep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos48/accepted_48.png"))); // NOI18N
        btacep.setText("aceptar");
        btacep.addActionListener(this::btacepActionPerformed);

        btcanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos48/button_cancel (4).png"))); // NOI18N
        btcanc.setText("cancelar");
        btcanc.addActionListener(this::btcancActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxpues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfnom))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btbusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btacep)
                        .addGap(36, 36, 36)
                        .addComponent(btcanc)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txfnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxpues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btacep)
                    .addComponent(btcanc)
                    .addComponent(btbusca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void llenarpuesto() {
    cbxpues.removeAllItems();
    cbxpues.addItem("Todos");
    for (Puesto puesto : Puesto.values()) {
        cbxpues.addItem(puesto.toString());
    }
}
     private void tablabuscar() {
    DefaultTableModel modelo = (DefaultTableModel) tblbusca.getModel();
    modelo.setRowCount(0);
    for (Empleado empleado : controlador.getEmpleados()) {
        modelo.addRow(new Object[]{
            empleado.getID(),
            empleado.getNombre(),
            empleado.getTelefono(),
            empleado.getPuesto(),
            empleado.getSalario()
        });
    }
}
    private void cbxpuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxpuesActionPerformed
      
    }//GEN-LAST:event_cbxpuesActionPerformed

    private void btbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscaActionPerformed
         DefaultTableModel modelo = (DefaultTableModel) tblbusca.getModel();
          modelo.setRowCount(0);
          String ID = txfid.getText();
          String nombre = txfnom.getText();
          String puestoSele = cbxpues.getSelectedItem().toString();
          for (Empleado empleado : controlador.getEmpleados()) {
               boolean bID = ID.isEmpty() || empleado.getID().contains(ID);
                boolean bNombre = nombre.isEmpty() || empleado.getNombre().contains(nombre);
                 boolean bPuesto = puestoSele.equals("Todos") || 
                         empleado.getPuesto().toString().equals(puestoSele);
                  if (bID && bNombre && bPuesto) {

            modelo.addRow(new Object[]{
                empleado.getID(),
                empleado.getNombre(),
                empleado.getTelefono(),
                empleado.getPuesto(),
                empleado.getSalario()
            });
          }
        }
    }//GEN-LAST:event_btbuscaActionPerformed

    private void btcancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancActionPerformed
        dispose();
    }//GEN-LAST:event_btcancActionPerformed

    private void btacepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacepActionPerformed
         int fila = tblbusca.getSelectedRow();
          if (fila == -1) {
        JOptionPane.showMessageDialog(this,"Seleccione un empleado"
        ); 
          }else{ String ID = tblbusca.getValueAt(fila, 0).toString();
          Empleado empleado = controlador.buscarEmpleado(ID);
          if (empleado == null) {
              JOptionPane.showMessageDialog(this, "No se encontró el empleado seleccionado.");
              return;
          }
          if (frmEmpleado != null) {
              frmEmpleado.buscarEmpleado(empleado);
          } else {
              registroEmpleado ventana = new registroEmpleado();
              ventana.buscarEmpleado(empleado);
              ventana.setVisible(true);
          }
          dispose();
    }
    }//GEN-LAST:event_btacepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btacep;
    private javax.swing.JButton btbusca;
    private javax.swing.JButton btcanc;
    private javax.swing.JComboBox<String> cbxpues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbusca;
    private javax.swing.JTextField txfid;
    private javax.swing.JTextField txfnom;
    // End of variables declaration//GEN-END:variables
}
