/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empleados;

import javax.swing.JOptionPane;
import excepciones.IDduplicadaException;
import excepciones.EmpleadoNoencontradoException;
/**
 *
 * @author EMMAXZZ
 */
public class registroEmpleado extends javax.swing.JFrame {
    public gestorEmpleado gestor;
    public ControladorEmpleado controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registroEmpleado.class.getName());
      
    /**
     * Creates new form registroEmpleado
     */
    public registroEmpleado() {
        initComponents();
        
        gestor = new gestorEmpleado();
        controlador = new ControladorEmpleado (gestor);
        
        cbxpuesto.removeAllItems();
        
        for(Puesto puesto : Puesto.values()){
            cbxpuesto.addItem(puesto.toString());
        }
       
        
        
    }
    public void buscarEmpleado(Empleado empleado) {
    txtID.setText(empleado.getID());
    txtNOM.setText(empleado.getNombre());
    txtTEL.setText(empleado.getTelefono());

    cbxpuesto.setSelectedItem(
            empleado.getPuesto().toString()
    );
    txfsalario.setText(
            String.valueOf(empleado.getSalario())
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNOM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTEL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxpuesto = new javax.swing.JComboBox<>();
        btguardar = new javax.swing.JButton();
        btbuscar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btactualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txfsalario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel1.setText("   REGISTRO DE EMPLEADOS");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setText("Identificación:");

        txtID.addActionListener(this::txtIDActionPerformed);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setText("Nombre completo:");

        txtNOM.addActionListener(this::txtNOMActionPerformed);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("Telefono:");

        txtTEL.addActionListener(this::txtTELActionPerformed);

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setText("Puesto:");

        cbxpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxpuesto.setName(""); // NOI18N
        cbxpuesto.addActionListener(this::cbxpuestoActionPerformed);

        btguardar.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btguardar.setText("Guardar");
        btguardar.addActionListener(this::btguardarActionPerformed);

        btbuscar.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btbuscar.setText("Buscar");
        btbuscar.addActionListener(this::btbuscarActionPerformed);

        bteliminar.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        bteliminar.setText("Eliminar");
        bteliminar.addActionListener(this::bteliminarActionPerformed);

        btactualizar.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btactualizar.setText("Actualizar");
        btactualizar.addActionListener(this::btactualizarActionPerformed);

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setText("Salario:");

        txfsalario.setEditable(false);

        jButton1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jButton1.setText("Limpiar campos");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNOM, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTEL, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txfsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)))
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txfsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMActionPerformed

    private void txtTELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTELActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        try{
            String ID = txtID.getText();
            String Nombre = txtNOM.getText();
            String telefono =txtTEL.getText();
            Puesto puesto = Puesto.valueOf(cbxpuesto.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this,"Se guardo correctamente el empleado");
            controlador.agregarEmpleado(ID, Nombre, telefono, puesto);
            
        } catch (IDduplicadaException i){
            JOptionPane.showMessageDialog(this, i.getMessage());
        }
    }//GEN-LAST:event_btguardarActionPerformed

    private void cbxpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxpuestoActionPerformed
      if(cbxpuesto.getSelectedItem()!= null){
          Puesto puesto = Puesto.valueOf(cbxpuesto.getSelectedItem().toString());
          txfsalario.setText(String.valueOf(puesto.getSalario()));
      }
    }//GEN-LAST:event_cbxpuestoActionPerformed

    private void btactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarActionPerformed
        try{
            String ID = txtID.getText();
            String Nombre = txtNOM.getText();
            String telefono = txtTEL.getText();
             Puesto puesto = Puesto.valueOf(
             cbxpuesto.getSelectedItem().toString()
        );
             controlador.actualizarempleado(ID, Nombre, telefono, puesto);
             JOptionPane.showMessageDialog(this, "Se actualizo el empleado correctamente");
        } catch(EmpleadoNoencontradoException no){
            JOptionPane.showMessageDialog(this, no.getMessage());

        }
    }//GEN-LAST:event_btactualizarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
       try{
           String ID =  txtID.getText();
           controlador.eliminarEmpleado(ID);
           JOptionPane.showMessageDialog(this, "Se elimino correctamente el empleado");
       } catch (EmpleadoNoencontradoException D){
           JOptionPane.showMessageDialog(this,D.getMessage());
       }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
      FrmbuscarEmpleado buscar = new FrmbuscarEmpleado(controlador, this);
      buscar.setVisible(true);
    }//GEN-LAST:event_btbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    txtID.setText("");
    txtNOM.setText("");
    txtTEL.setText("");
    txfsalario.setText("");
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registroEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btactualizar;
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btguardar;
    private javax.swing.JComboBox<String> cbxpuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txfsalario;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNOM;
    private javax.swing.JTextField txtTEL;
    // End of variables declaration//GEN-END:variables
}
